apiVersion: v1
kind: Service
metadata:
  name: critical-service
spec:
  type: NodePort
  selector:
    app: critical-app
  ports:
    - name: http        # REQUIRED
      port: 8000
      targetPort: 8000
      nodePort: 30017
